version: '2'

services:
  app:
    image: 'api:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=hotel
      - POSTGRES_PASSWORD=hotel